name: python test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: List dir
        run: dir
      - name: Check version
        run: python --version
      - name: install package
        run: |
          python -m pip install --upgrade pip
          pip install pytest
      - name: Install plugin
        run: pip install pytest-github-actions-annotate-failures
      - name: Run test
        run: pytest